### ISSUE TITLE
Comments in schedule deck input files are stripped

### ISSUE THREAD

**Issue by berland** [Statoil/sunbeam#80]
It seems that TimeVector.load('somefile.sch') will drop all comment (starting with '--') in somefile.sch. Can this be relaxed, it can be very handy for later debugging to be able to keep comments in their original places (or nearby)?

**Comment by joakim-hove** [comment]
> Can this be relaxed, it can be very handy for later debugging to be able to keep comments in their original places (or nearby)?

I am sorry - no; I understand that keeping the comments would be highly valuable, but the comments are stripped away - and dropped on the floor, quite early and very deep into the parsing code. I am sorry - but I will have to close this as unfeasable ;-(
