### ISSUE TITLE
Suppress start_date on TimeVector string output

### ISSUE THREAD

**Issue by berland** [Statoil/sunbeam#81]
The `TimeVector.__str__` method should suppress outputting `DATES` for the `start_date`. Eclipse knows the start date already through the `START` keyword, and `TimeVector.start_date` should in general correspond to the Eclipse START-date. Eclipse will error if it encounters a date equal or less than the date in `START`.

The following should then return an empty string (modulo whitespace):
```
from sunbeam.tools import TimeVector
import datetime
voidsch = TimeVector(datetime.date(2020,1,1))
str(voidsch)
```

**Comment by lahus2** [comment]
Agreed, I think #75 discussed this and gave some answers about how it should work.

**Comment by berland** [comment]
#75 is closed and fixed, so there is more to it.

**Comment by joakim-hove** [comment]
OK: this should be fixed here: https://github.com/Statoil/sunbeam/pull/82

**Comment by berland** [comment]
Confirmed.
