### ISSUE TITLE
error building sunbeam: "class _LIBCPP_TEMPLATE_VIS basic_string"

### ISSUE THREAD

**Issue by dhan16** [Statoil/sunbeam#87]
I'm developing on macOS. 
1. Cloned libecl and opm-common and built them
2. on building sunbeam, I get the below error:

[ 37%] Building CXX object sunbeam/CMakeFiles/libsunbeam.dir/eclipse_config.cpp.o
In file included from /Users/dhan/work/opm/sunbeam/sunbeam/eclipse_config.cpp:2:
In file included from /Users/dhan/install/include/opm/parser/eclipse/EclipseState/EclipseConfig.hpp:25:
/Users/dhan/install/include/opm/parser/eclipse/EclipseState/InitConfig/InitConfig.hpp:45:21: error: implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
        std::string m_restartRootName;
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iosfwd:193:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
1 error generated.
make[2]: *** [sunbeam/CMakeFiles/libsunbeam.dir/eclipse_config.cpp.o] Error 1
make[1]: *** [sunbeam/CMakeFiles/libsunbeam.dir/all] Error 2
make: *** [all] Error 2

**Comment by dhan16** [comment]
I think this is due to a missing "include <string>" in InitConfig.hpp in opm-common. so i can fix this in two ways:

1. Add the include to InitConfig.hpp in opm-common

OR

2. Add to sunbeam/eclipse_config.cpp

What is the convention here? I'd think header files need to be self-sufficient so the right fix is in opm-common. 

Thoughts?

**Comment by joakim-hove** [comment]
OK - thank you for your report; will take some time before we can look properly into it. From looking at your error message I would say it looks like the real problem is actually in opm-common and not in Sunbeam?

**Comment by joakim-hove** [comment]
> Add the include to InitConfig.hpp in opm-common

Cool if you make a PR on that.

**Comment by dhan16** [comment]
thanks will do!

**Comment by dhan16** [comment]
created https://github.com/OPM/opm-common/issues/474

**Comment by dhan16** [comment]
fixed and merged to master in opm-common
